name: Preview PHP Site via Cloudflare Tunnel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  serve:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code (index.html, fV9o.php)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install PHP
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # 3. Clean and recreate the cache directory
      - name: Clean CoinImp cache directory
        run: |
          rm -rf coinimp-cache
          mkdir -p coinimp-cache
          chmod 777 coinimp-cache

      # 4. Install Cloudflared
      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      # 5. Start PHP server and open Tunnel
      - name: Serve & Tunnel
        run: |
          # start PHP built-in server in the background
          php -S 0.0.0.0:8080 -t . &
          # open a free quick Tunnel; logs the public URL
          cloudflared tunnel --url http://localhost:8080
